[project]
name = "cs4-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "channels>=4.3.2",
    "daphne>=4.2.1",
    "dj-database-url>=3.0.1",
    "django>=6.0",
    "whitenoise>=6.11.0",
]
